'use client';
import {Canvas,useFrame,useThree} from '@react-three/fiber';
import {Environment,Float,OrbitControls,Stars,Text, useTexture} from '@react-three/drei';
import {EffectComposer,Bloom,DepthOfField,Vignette,Noise,ChromaticAberration} from '@react-three/postprocessing';
import * as THREE from 'three';
import {useEffect,useMemo,useRef} from 'react';
import {useWorldStore} from '../lib/store';

function Terrain(){const ref=useRef<THREE.Mesh>(null);const geo=useMemo(()=>{const g=new THREE.PlaneGeometry(70,180,80,160);const p=g.attributes.position;for(let i=0;i<p.count;i++){const x=p.getX(i),y=p.getY(i);p.setZ(i,Math.sin(x*.21)*.7+Math.sin(y*.11)*.55+Math.sin((x+y)*.06)*.8+Math.random()*.14)}g.computeVertexNormals();return g},[]);return <mesh ref={ref} geometry={geo} rotation-x={-Math.PI/2} position={[0,-1.2,-45]} receiveShadow><meshStandardMaterial color="#17100e" roughness={1} metalness={.08}/></mesh>}
function Mountains(){return <group position={[0,4,-72]}>{Array.from({length:13}).map((_,i)=>{const x=(i-6)*9;const h=10+(i%4)*3;return <mesh key={i} position={[x,h/2,0]}><coneGeometry args={[7,h,6]} /><meshStandardMaterial color="#080a0d" roughness={1}/></mesh>})}</group>}
function Gate({z}:{z:number}){const left=useRef<THREE.Mesh>(null),right=useRef<THREE.Mesh>(null);useFrame(()=>{const p=useWorldStore.getState().progress;const local=THREE.MathUtils.clamp((p-(Math.abs(z)/180-.08))/.09,0,1);if(left.current)left.current.rotation.y=THREE.MathUtils.lerp(0,.72,local);if(right.current)right.current.rotation.y=THREE.MathUtils.lerp(0,-.72,local)});return <group position={[0,3,z]}>{[-1,1].map(s=><group key={s} position={[s*5,0,0]}><mesh><cylinderGeometry args={[.75,.9,12,10]}/><meshStandardMaterial color="#30110b" metalness={.35} roughness={.55} emissive="#2c0d07" emissiveIntensity={1}/></mesh></group>)}<mesh position={[0,8,0]}><boxGeometry args={[13,1,1]}/><meshStandardMaterial color="#5b1a0c" metalness={.25} roughness={.5} emissive="#321006" emissiveIntensity={1}/></mesh><mesh ref={left} position={[-3.2,4.5,.25]}><boxGeometry args={[4.6,7,.35]}/><meshStandardMaterial color="#4b160b" roughness={.65} emissive="#1b0805" emissiveIntensity={1}/></mesh><mesh ref={right} position={[3.2,4.5,.25]}><boxGeometry args={[4.6,7,.35]}/><meshStandardMaterial color="#4b160b" roughness={.65} emissive="#1b0805" emissiveIntensity={1}/></mesh></group>}
function Fire(){const light=useRef<THREE.PointLight>(null);const flame=useRef<THREE.Mesh>(null);useFrame(({clock})=>{const t=clock.elapsedTime;if(light.current)light.current.intensity=7+Math.sin(t*8)*1.4+Math.sin(t*17)*.8;if(flame.current)flame.current.scale.y=1+Math.sin(t*9)*.12});return <group position={[0,1,-30]}><pointLight ref={light} color="#ff5a1f" distance={42} intensity={8} castShadow/><mesh ref={flame} position={[0,1.8,0]}><icosahedronGeometry args={[4,2]}/><meshStandardMaterial color="#ff4d0b" emissive="#ff2600" emissiveIntensity={5} roughness={.25}/></mesh><mesh position={[0,3.6,0]}><coneGeometry args={[2.1,5.5,20]}/><meshStandardMaterial color="#ffb35c" emissive="#ff3b00" emissiveIntensity={7} transparent opacity={.78}/></mesh></group>}
function Embers(){const count=900;const positions=useMemo(()=>{const a=new Float32Array(count*3);for(let i=0;i<count;i++){a[i*3]=(Math.random()-.5)*45;a[i*3+1]=Math.random()*18-1;a[i*3+2]=-Math.random()*150}return a},[]);const ref=useRef<THREE.Points>(null);useFrame(({clock})=>{if(ref.current){const arr=ref.current.geometry.attributes.position.array as Float32Array;for(let i=0;i<count;i++){arr[i*3+1]+=.025;if(arr[i*3+1]>20)arr[i*3+1]=-1;arr[i*3]+=Math.sin(clock.elapsedTime*.7+i)*.002}ref.current.geometry.attributes.position.needsUpdate=true}});return <points ref={ref}><bufferGeometry><bufferAttribute attach="attributes-position" count={count} array={positions} itemSize={3}/></bufferGeometry><pointsMaterial size={.08} color="#ff7838" transparent opacity={.85} sizeAttenuation/></points>}
function CameraRig(){const {camera}=useThree();const mouse=useRef({x:0,y:0});useEffect(()=>{const f=(e:MouseEvent)=>{mouse.current.x=(e.clientX/innerWidth-.5);mouse.current.y=(e.clientY/innerHeight-.5)};addEventListener('mousemove',f);return()=>removeEventListener('mousemove',f)},[]);useFrame(()=>{const p=useWorldStore.getState().progress;const targetZ=5-p*145;camera.position.z=THREE.MathUtils.lerp(camera.position.z,targetZ,.08);camera.position.x=THREE.MathUtils.lerp(camera.position.x,mouse.current.x*.8,.05);camera.position.y=THREE.MathUtils.lerp(camera.position.y,2.2+mouse.current.y*-.5,.05);camera.rotation.y=THREE.MathUtils.lerp(camera.rotation.y,-mouse.current.x*.035,.05)});return null}
function Scene(){return <><color attach="background" args={['#020306']}/><fogExp2 attach="fog" args={['#0a080a',.035]}/><ambientLight intensity={.18}/><directionalLight position={[-8,15,8]} intensity={.5} color="#93a7c9"/><Stars radius={120} depth={90} count={2600} factor={1.5} saturation={0} fade speed={.15}/><Terrain/><Mountains/><Fire/><Embers/><Gate z={-8}/><Gate z={-55}/><Gate z={-105}/><Gate z={-142}/><CameraRig/><EffectComposer multisampling={0}><Bloom intensity={1.25} luminanceThreshold={.55} luminanceSmoothing={.35} mipmapBlur/><DepthOfField focusDistance={.018} focalLength={.035} bokehScale={2.2}/><ChromaticAberration offset={new THREE.Vector2(.00035,.00035)}/><Vignette darkness={.72} eskil={false}/><Noise premultiply opacity={.075}/></EffectComposer></>}
export default function World(){return <div className="fixed inset-0 z-0"><Canvas shadows dpr={[1,1.6]} camera={{position:[0,2.2,5],fov:55}} gl={{antialias:true,toneMapping:THREE.ACESFilmicToneMapping,toneMappingExposure:1.05}}><Scene/></Canvas></div>}
